### ISSUE TITLE
Is the code written for Python 2?

### ISSUE THREAD

**Issue by sushmitaagarwal** [samconnolly/DELightcurveSimulation#8]
I want to know if your code is written in python 2 and if it is, is there a version available for it in python 3? I see that the print command in the script is in python 2 format. It works well for me when I have a python 2 environment, but doesn't work if I run on python 3. 
Kindly let me know. It will help me in progressing my work. 
@samconnolly

**Comment by samconnolly** [comment]
This code was written for python 2.7. Sorry for the slow reply, this code hasn't been worked on for a long time now!
